services:
  nuxt-dev:
    build:
      context: ./nuxt
      dockerfile: Dockerfile.dev
    volumes:
      - ./nuxt:/workspase 
      - /workspase/node_modules
    working_dir: /workspase
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
    depends_on:
      - database
      
  # nuxt-prod:
  #   build:
  #     context: ./nuxt
  #     dockerfile: Dockerfile.prod
  #   ports:
  #     - 3001:3000
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
  #   depends_on:
  #     - database

  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:6.19
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 5050:80
    restart: unless-stopped
    depends_on:
      - database

volumes:
  pgdata:
  # nuxt-cache:
